
<div class="item">
    <h1>VCF (Variant Call Format) specification</h1>
    The newest versions of the VCF 4.1, VCF 4.2, and BCF specification documents can be found on github. The older versions of the documents are hosted on the 1000 genomes wiki page.
    <ul>
    <li>VCF format v4.0: <a href="http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40">1000 genomes wiki</a></li>
    <li>VCF format v4.1: <a href="http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-41">1000 genomes wiki</a> | <a href="https://github.com/samtools/hts-specs">github</a> </li>
	<li>VCF format v4.2: <a href="http://www.1000genomes.org/wiki/analysis/variant-call-format/vcf-variant-call-format-version-42">1000 genomes wiki</a> | <a href="https://github.com/samtools/hts-specs">github</a> </li>
    <li>BCF format v2.1: <a href="http://www.1000genomes.org/wiki/analysis/variant-call-format/bcf-binary-vcf-version-2">1000 genomes wiki</a> | <a href="https://github.com/samtools/hts-specs">github</a> -
    	Binary format designed for efficient storing and parsing of VCF records. BCF has been recently standardized
    	and implemented in tools such as <a href="https://github.com/samtools/htslib">htslib</A> (C library for high-throughput sequencing data formats)
    	and GATK.
    </li>
    </ul> 
    <br>
    <ul>
    <li><a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3137218/">VCF paper</a></li>
    <li><a href="VCF-poster.pdf">VCF poster</a></li>
    <li><A href="https://lists.sourceforge.net/lists/listinfo/vcftools-spec">VCFtools-spec</a> - Low traffic mailing list intended for VCF format related
        discussions, such as clarifications of the current format version or
        proposals of changes to the specification. 
        </li>
    </ul>
    <br>
    <ul>
    <li><a href="http://www.1000genomes.org/wiki/analysis/variant-call-format/bcf-binary-vcf-version-2">Binary Call Format (BCF)</a> - 
        Binary format designed for efficient storing and parsing of VCF records. BCF has been recently standardized 
        and implemented in tools such as <a href="https://github.com/samtools/htslib">htslib</A> (C library for high-throughput sequencing data formats)
        and GATK.
        </li>
    </ul>
</div>

